name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # weekly
  pull_request:

permissions: {}

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Validate renovate config
        run: nix-shell -p renovate --run "renovate-config-validator"

  renovate-local:
    runs-on: ubuntu-latest
    environment: renovate
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Sets env var for dry-run
        if: github.event_name == 'pull_request'
        run: echo "RENOVATE_DRY_RUN=full" >> $GITHUB_ENV

      - name: Renovate
        uses: renovatebot/github-action@6a9df9227eeb83af9a5abef6890bbb0c9068f436 # v46.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: .github/renovate.json
          docker-cmd-file: .github/renovate-entrypoint.sh
          docker-user: root
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_ALLOWED_COMMANDS: "^nix run github:Mic92/nix-update"
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: ${{ env.RENOVATE_DRY_RUN }}
